version: '3'

services:
  app:
    build: app
    container_name: php-poc-app
    depends_on:
      - db
    ports:
      - "80:80"
      - "443:443"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=www
      - MYSQL_PASSWORD=nXa7bu5H
    env_file:
      - mysql.env
  db:
    build: db
    container_name: php-poc-db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=www
      - MYSQL_PASSWORD=nXa7bu5H
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
