version: '3'

services:
  web:
    volumes:
      - ./web/php:/var/www/html
    stdin_open: true
    tty: true
  db:
    ports:
      - "6612:3306"
    volumes:
      - ./db/initdb-entrypoint.d:/docker-entrypoint-initdb.d
