version: '3'

services:
  app:
    volumes:
      - ./app:/var/www/html
    stdin_open: true
    tty: true
  db:
    ports:
      - "3306:3306"
    volumes:
      - ./db/initdb-entrypoint.d:/docker-entrypoint-initdb.d
