version: '3'

services:
  app:
    volumes:
      - ./app/public:/app/public
      - ./app/mvc:/app/mvc
    stdin_open: true
    tty: true
  db:
    ports:
      - "6612:3306"
    volumes:
      - ./db/initdb-entrypoint.d:/docker-entrypoint-initdb.d
